version: "3.6"
services:
  app:
    build:
      context: .
      target: development
    command: ["node", "./script/server.js"]
    environment:
      - CERT=/home/node/certificates
      - ENV=/home/node/shell/ash.sh
      - HOST=localhost
      - PORT=8080
      - PROJECT=node.js
    ports:
      - "8443:8080"
    tty: true
    volumes:
      - certificates:/home/node/certificates
      - shell:/home/node/shell
      - ./config:/home/node/config
      - ./public:/home/node/app/public
      - ./script:/home/node/app/script
    working_dir: /home/node/app
volumes:
  certificates:
    external: true
  shell:
    external: true
